version: '3'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  your-app:
    build:
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - nats
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - nats
